class ApiConstants {
  static const String baseUrl = 'https://aura-movies-scraper.vercel.app';

  static const Map<String, List<String>> languageMap = {
    'ar': ['arabic', 'ar', 'ara', 'arb', 'عربي', 'العربية'],
    'fa': ['persian', 'fa', 'fas', 'per', 'farsi', 'فارسی'],
    'he': ['hebrew', 'he', 'heb', 'عبرية', 'עברית'],
    'ur': ['urdu', 'ur', 'urd', 'أوردو', 'اردو'],
    'am': ['amharic', 'am', 'amh'],
    'sw': ['swahili', 'sw', 'swa', 'kiswahili'],

    'en': [
      'english',
      'en',
      'eng',
      'en-us',
      'en-gb',
      'english (us)',
      'english (uk)',
    ],
    'es': [
      'spanish',
      'es',
      'esp',
      'spa',
      'español',
      'castellano',
      'es-es',
      'es-mx',
      'es-419',
      'latino',
      'spanish (latin america)',
    ],
    'fr': ['french', 'fr', 'fra', 'fre', 'français', 'fr-fr', 'fr-ca'],
    'de': ['german', 'de', 'ger', 'deu', 'deutsch'],
    'it': ['italian', 'it', 'ita', 'italiano'],
    'pt': [
      'portuguese',
      'pt',
      'por',
      'português',
      'pt-br',
      'pt-pt',
      'pob',
      'pb',
    ],
    'ru': ['russian', 'ru', 'rus', 'русский'],
    'uk': ['ukrainian', 'uk', 'ukr', 'українська'],
    'pl': ['polish', 'pl', 'pol', 'polski'],
    'nl': ['dutch', 'nl', 'nld', 'dut', 'nederlands'],

    'zh': [
      'chinese',
      'zh',
      'chi',
      'zho',
      'cn',
      'zh-cn',
      'zh-tw',
      'zh-hk',
      'mandarin',
      'cantonese',
      'zht',
      'zhs',
      '中文',
      '汉语',
      '漢語',
    ],
    'ja': ['japanese', 'ja', 'jap', 'jpn', 'jp', '日本語'],
    'ko': ['korean', 'ko', 'kor', 'kr', '한국어'],
    'vi': ['vietnamese', 'vi', 'vie', 'tiếng việt'],
    'th': ['thai', 'th', 'tha', 'ไทย'],
    'id': ['indonesian', 'id', 'ind', 'bahasa indonesia'],
    'ms': ['malay', 'ms', 'may', 'msa'],
    'fil': ['filipino', 'fil', 'tl', 'tgl', 'tagalog'],

    'hi': ['hindi', 'hi', 'hin', 'हिंदी'],
    'ta': ['tamil', 'ta', 'tam', 'தமிழ்'],
    'te': ['telugu', 'te', 'tel', 'తెలుగు'],
    'ml': ['malayalam', 'ml', 'mal', 'മലയാളം'],
    'kn': ['kannada', 'kn', 'kan', 'ಕನ್ನಡ'],
    'mr': ['marathi', 'mr', 'mar', 'मराठी'],
    'bn': ['bengali', 'bn', 'ben', 'bangla', 'বাংলা'],
    'pa': ['punjabi', 'pa', 'pan'],
    'gu': ['gujarati', 'gu', 'guj'],

    'sv': ['swedish', 'sv', 'swe', 'svenska'],
    'no': ['norwegian', 'no', 'nor', 'norsk'],
    'da': ['danish', 'da', 'dan', 'dansk'],
    'fi': ['finnish', 'fi', 'fin', 'suomi'],
    'el': ['greek', 'el', 'gre', 'ell', 'ellinika', 'ελληνικά'],
    'tr': ['turkish', 'tr', 'tur', 'türkçe'],
    'cs': ['czech', 'cs', 'cze', 'ces', 'čeština'],
    'sk': ['slovak', 'sk', 'slo', 'slk'],
    'hu': ['hungarian', 'hu', 'hun', 'magyar'],
    'ro': ['romanian', 'ro', 'rum', 'ron', 'română'],
    'bg': ['bulgarian', 'bg', 'bul', 'български'],
    'sr': ['serbian', 'sr', 'srp'],
    'hr': ['croatian', 'hr', 'hrv'],
    'bs': ['bosnian', 'bs', 'bos'],
    'sl': ['slovenian', 'sl', 'slv'],
    'sq': ['albanian', 'sq', 'alb', 'sqi'],
    'mk': ['macedonian', 'mk', 'mac', 'mkd'],
    'et': ['estonian', 'et', 'est'],
    'lv': ['latvian', 'lv', 'lav'],
    'lt': ['lithuanian', 'lt', 'lit'],
    'is': ['icelandic', 'is', 'ice', 'isl'],
    'be': ['belarusian', 'be', 'bel'],

    'ca': ['catalan', 'ca', 'cat'],
    'eu': ['basque', 'eu', 'baq', 'eus'],
    'gl': ['galician', 'gl', 'glg'],
    'ka': ['georgian', 'ka', 'geo', 'kat'],
    'hy': ['armenian', 'hy', 'arm', 'hye'],
    'az': ['azerbaijani', 'az', 'aze'],
    'kk': ['kazakh', 'kk', 'kaz'],
    'uz': ['uzbek', 'uz', 'uzb'],
  };
}
